### ISSUE TITLE
A next.js server with nebula-node was failed to build.

### ISSUE THREAD

**Issue by yusangeng** [nebula-contrib/nebula-node#29]
next.js version: 14.2.3

nebula-node version: 3.0.3

Error detail:

```
npm run build

> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.13

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
   Collecting page data  .Error: Could not locate the bindings file. Tried:
 → D:\workspace\graph-echart-demo\my-app\.next\build\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\build\Debug\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\build\Release\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\out\Debug\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\Debug\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\out\Release\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\Release\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\build\default\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\compiled\20.17.0\win32\x64\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\addon-build\release\install-root\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\addon-build\debug\install-root\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\addon-build\default\install-root\addon.node
 → D:\workspace\graph-echart-demo\my-app\.next\lib\binding\node-v115-win32-x64\addon.node
    at t (D:\workspace\graph-echart-demo\my-app\.next\server\app\api\get-graph-data\route.js:1:165646)
    at 3882 (D:\workspace\graph-echart-demo\my-app\.next\server\app\api\get-graph-data\route.js:1:3008)
    at t (D:\workspace\graph-echart-demo\my-app\.next\server\webpack-runtime.js:1:143)
    at 7958 (D:\workspace\graph-echart-demo\my-app\.next\server\app\api\get-graph-data\route.js:1:93185)
    at t (D:\workspace\graph-echart-demo\my-app\.next\server\webpack-runtime.js:1:143)
    at 2920 (D:\workspace\graph-echart-demo\my-app\.next\server\app\api\get-graph-data\route.js:1:92300)
    at t (D:\workspace\graph-echart-demo\my-app\.next\server\webpack-runtime.js:1:143)
    at 3912 (D:\workspace\graph-echart-demo\my-app\.next\server\app\api\get-graph-data\route.js:1:6683)
    at t (D:\workspace\graph-echart-demo\my-app\.next\server\webpack-runtime.js:1:143)
    at 1369 (D:\workspace\graph-echart-demo\my-app\.next\server\app\api\get-graph-data\route.js:1:3316) {
  tries: [
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\build\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\build\\Debug\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\build\\Release\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\out\\Debug\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\Debug\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\out\\Release\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\Release\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\build\\default\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\compiled\\20.17.0\\win32\\x64\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\addon-build\\release\\install-root\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\addon-build\\debug\\install-root\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\addon-build\\default\\install-root\\addon.node',
    'D:\\workspace\\graph-echart-demo\\my-app\\.next\\lib\\binding\\node-v115-win32-x64\\addon.node'
  ]
}

> Build error occurred
Error: Failed to collect page data for /api/get-graph-data
    at D:\workspace\graph-echart-demo\my-app\node_modules\next\dist\build\utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

**Comment by zhanghuidinah** [comment]
@wey-gu PTAL
